add_newline = true
format = """
[┌───────────────────>](bold green)
[│](bold green)$directory$package
[└─>](bold green) """

[character]
success_symbol = "[➜](bold green)"

[package]
disabled = true

[git_branch]
symbol = "🌱 "
truncation_symbol = ""
format = "on [$symbol$branch]($style) "


